# Generated by Django 6.0.1 on 2026-01-11 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Marka")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "production_year",
                    models.PositiveIntegerField(verbose_name="Rok produkcji"),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Cena za dobę (PLN)",
                    ),
                ),
                (
                    "gearbox",
                    models.CharField(
                        choices=[("manual", "Manualna"), ("automatic", "Automatyczna")],
                        default="manual",
                        max_length=20,
                        verbose_name="Skrzynia biegów",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Dostępny"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cars/", verbose_name="Zdjęcie"
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis wyposażenia")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to="service.category",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Samochód",
                "verbose_name_plural": "Samochody",
            },
        ),
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data rozpoczęcia")),
                ("end_date", models.DateField(verbose_name="Data zakończenia")),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Koszt całkowity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="service.car",
                        verbose_name="Samochód",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wypożyczenie",
                "verbose_name_plural": "Wypożyczenia",
                "ordering": ["-created_at"],
            },
        ),
    ]
