# Generated by Django 6.0.1 on 2026-01-24 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('production_year', models.PositiveIntegerField(verbose_name='Rok produkcji')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za dobę (PLN)')),
                ('gearbox', models.CharField(choices=[('manual', 'Manualna'), ('automatic', 'Automatyczna')], default='manual', max_length=20, verbose_name='Skrzynia biegów')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Zdjęcie główne')),
                ('description', models.TextField(verbose_name='Opis wyposażenia')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa koloru')),
                ('hex_code', models.CharField(help_text='np. #FF0000', max_length=7, verbose_name='Kod HEX')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Liczba sztuk we flocie')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='service.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='service.category', verbose_name='Kategoria'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Koszt całkowity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_accepted', models.BooleanField(default=False, verbose_name='Dodatkowe ubezpieczenie (+50 PLN)')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi do rezerwacji')),
                ('payment_method', models.CharField(choices=[('card', 'Karta kredytowa/debetowa'), ('transfer', 'Przelew tradycyjny'), ('blik', 'BLIK'), ('cash', 'Gotówka przy odbiorze')], default='card', max_length=20, verbose_name='Metoda płatności')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='service.car', verbose_name='Samochód')),
                ('car_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='service.carcolor', verbose_name='Wybrany wariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres zamieszkania')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
