# Generated by Django 6.0.1 on 2026-01-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="insurance_accepted",
            field=models.BooleanField(
                default=False, verbose_name="Dodatkowe ubezpieczenie (+50 PLN)"
            ),
        ),
        migrations.AddField(
            model_name="rental",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Uwagi do rezerwacji"),
        ),
    ]
