# Generated by Django 6.0.1 on 2026-01-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_rental_insurance_accepted_rental_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Karta kredytowa/debetowa"),
                    ("transfer", "Przelew tradycyjny"),
                    ("blik", "BLIK"),
                    ("cash", "Gotówka przy odbiorze"),
                ],
                default="card",
                max_length=20,
                verbose_name="Metoda płatności",
            ),
        ),
    ]
